### DISCUSSION TITLE
how to view my book on a single page

### DISCUSSION THREAD

**Discussion by hi-sonu** [readest/readest#561] [General]
Is it possible to view it as a single page? By default, it opens in a two-page side-by-side view, which makes it hard to read my book.
![brave_screenshot_web readest com](https://github.com/user-attachments/assets/82e2ff97-07d8-4cca-9d42-bc4d54a9d04d)

**Comment by blue-bird1** [comment]
set css 
```css
foliate-view {
  width: 50%;
  overflow: scroll;
  margin: 0 auto;
}
```
