### ISSUE TITLE
FR: Flatpak Support

### ISSUE THREAD

**Issue by NN708** [readest/readest#71]
I would like to propose the addition of Flatpak support for Readest. [Flatpak](https://flatpak.org/) is a distribution-agnostic packaging system for Linux that allows applications to run in a sandboxed environment. Many popular Linux distributions come with Flatpak pre-installed. By publishing Readest on [Flathub](https://flathub.org/), users can install this application effortlessly.

**Comment by chrox** [comment]
So what's the form of Flatpak distribution? Is it just an all in one file like .AppImage file that we can auto build in the GitHub workflow and upload automatically? Or is it like the Apple Store we need to manually upload each version and wait for the review of the release? If it's the former one we can try it out, if it's the latter one we don't have enough resource to do that for each release.

**Comment by NN708** [comment]
It's somewhat of a middle ground. If we use Flathub, it offers a Buildbot that automatically generates pull requests and builds for each release using its own infrastructure. The only manual step required is merging those pull requests. I have some experience with that and would be happy to assist with the submission.

**Comment by chrox** [comment]
That will be great. I will check on this. Thanks.

**Comment by iskandergaba** [comment]
Re-igniting this: https://v2.tauri.app/distribute/flatpak/

It would be terrific to have Readest as an official Flatpak package. It would simplify the update user experience so much.

**Comment by chrox** [comment]
My Ubuntu virtual machine was dead. Maybe I can setup a new one this week and then test the flatpak build.

**Comment by archisman-panigrahi** [comment]
Any updates?

**Comment by chrox** [comment]
Currently none of Readest's OAuth flows works with flatpak's sandboxed environment, namely the custom schema way to launch readest with readest://oauth-callback and a custom way to open and listen to a HTTP port for oauth callback. This is a blocker for the flatpak release. Maybe someone more familiar with flatpak can help with this.

**Comment by chrox** [comment]
Except for the OAuth to login with the cloud account, reading functions look normal in Flatpak environment. For anyone who has interests on this, a manifest to build a Flatpak package is the following:

```yaml
id: com.bilingify.readest

runtime: org.gnome.Platform
runtime-version: "47"
sdk: org.gnome.Sdk

command: readest
finish-args:
  - --socket=wayland
  - --socket=fallback-x11
  - --device=dri
  - --share=ipc

modules:
  - name: binary
    buildsystem: simple
    sources:
      - type: file
        url: https://github.com/readest/readest/releases/download/v0.9.37/Readest_0.9.37_amd64.deb
        sha256: 19bead514e592fabf84352db3742fa93be03e82fee1c84bc1acf6ccd5df18305
        only-arches: [x86_64]
      - type: file
        url: https://github.com/readest/readest/releases/download/v0.9.37/Readest_0.9.37_arm64.deb
        sha256: bb36ee60d8b710f376a961317089393707a3106c9e6cbd26d472a872b2f13360
        only-arches: [aarch64]
    build-commands:
      - ar -x *.deb
      - tar -xf data.tar.gz
      - install -Dm755 usr/bin/readest /app/bin/readest
      - install -Dm644 usr/share/applications/Readest.desktop /app/share/applications/com.bilingify.readest.desktop
      - sed -i 's/^Icon=.*$/Icon=com.bilingify.readest/' /app/share/applications/com.bilingify.readest.desktop
      - install -Dm644 usr/share/icons/hicolor/128x128/apps/readest.png /app/share/icons/hicolor/128x128/apps/com.bilingify.readest.png
      - install -Dm644 usr/share/icons/hicolor/32x32/apps/readest.png /app/share/icons/hicolor/32x32/apps/com.bilingify.readest.png
      - install -Dm644 usr/share/icons/hicolor/256x256@2/apps/readest.png /app/share/icons/hicolor/256x256/apps/com.bilingify.readest.png
      - install -Dm644 usr/share/icons/hicolor/256x256@2/apps/readest.png /app/share/icons/hicolor/256x256@2/apps/com.bilingify.readest.png
      - install -Dm644 /dev/null /app/share/icons/hicolor/index.theme
      - gtk-update-icon-cache -f /app/share/icons/hicolor

```

**Comment by archisman-panigrahi** [comment]
> namely the custom scheme way to launch readest with readest://oauth-callback and a custom way to open and listen to a HTTP port for oauth callback

What is the role of these? How can I test them? (I have not used the cloud sync of readest yet, maybe they are related?)

**Comment by iskandergaba** [comment]
> Currently none of Readest's OAuth flows works with flatpak's sandboxed environment, namely the custom scheme way to launch readest with readest://oauth-callback and a custom way to open and listen to a HTTP port for oauth callback. This is a blocker for the flatpak release. Maybe someone more familiar with flatpak can help with this.

I tried and tested a few things, but for now, the callback opens a new instance of Readest instead of the original one. Is that what you are experiencing?

**Comment by chrox** [comment]
> What is the role of these? How can I test them? (I have not used the cloud sync of readest yet, maybe they are related?)

We use this to login and sync across devices.

**Comment by chrox** [comment]
> I tried and tested a few things, but for now, the callback opens a new instance of Readest instead of the original one. Is that what you are experiencing?

Yes, exactly.

**Comment by iskandergaba** [comment]
Alright. I spent some time on this, and while unfortunately I am still unable to fix the callbacks' problem, I fixed a small bug with your manifest and made a few improvements to your manifest that are worth keeping track of.

Below is my slightly modified version of the manifest:

```yml
id: com.bilingify.readest

runtime: org.gnome.Platform
runtime-version: "48"
sdk: org.gnome.Sdk

command: readest
finish-args:
  - --socket=wayland
  - --socket=fallback-x11
  - --device=dri
  - --share=ipc

modules:
  - name: binary
    buildsystem: simple
    sources:
      - type: file
        url: https://github.com/readest/readest/releases/download/v0.9.37/Readest_0.9.37_amd64.deb
        sha256: 19bead514e592fabf84352db3742fa93be03e82fee1c84bc1acf6ccd5df18305
        only-arches: [x86_64]
      - type: file
        url: https://github.com/readest/readest/releases/download/v0.9.37/Readest_0.9.37_arm64.deb
        sha256: bb36ee60d8b710f376a961317089393707a3106c9e6cbd26d472a872b2f13360
        only-arches: [aarch64]
    build-commands:
      - ar -x *.deb
      - tar -xf data.tar.gz
      - install -Dm755 usr/bin/readest /app/bin/readest
      - install -Dm644 usr/share/applications/Readest.desktop /app/share/applications/com.bilingify.readest.desktop
      - install -Dm644 usr/share/icons/hicolor/128x128/apps/readest.png /app/share/icons/hicolor/128x128/apps/com.bilingify.readest.png
      - install -Dm644 usr/share/icons/hicolor/32x32/apps/readest.png /app/share/icons/hicolor/32x32/apps/com.bilingify.readest.png
      - install -Dm644 usr/share/icons/hicolor/256x256@2/apps/readest.png /app/share/icons/hicolor/256x256/apps/com.bilingify.readest.png
      - install -Dm644 usr/share/icons/hicolor/256x256@2/apps/readest.png /app/share/icons/hicolor/256x256@2/apps/com.bilingify.readest.png
      - install -Dm644 /dev/null /app/share/icons/hicolor/index.theme
      - desktop-file-edit --set-key=Exec --set-value='readest %u' /app/share/applications/com.bilingify.readest.desktop
      - desktop-file-edit --set-key=Icon --set-value='com.bilingify.readest' /app/share/applications/com.bilingify.readest.desktop
      - gtk-update-icon-cache -f /app/share/icons/hicolor
```

- **Fixes:**
    - Add `- desktop-file-edit --set-key=Exec --set-value='readest %u' /app/share/applications/com.bilingify.readest.desktop` to ensure that double-clicking an ePub file (or any other file that Readest can handle) would open it in Readest properly. Before adding this, Readest would open a blank screen upon clicking a supported file.

- **Improvements:**
    - Upgrade Gnome SDK to the latest stable version.
    - Replace `sed` command with `desktop-file-edit` for a cleaner and more maintainable manifest.

I can't figure out quite yet why the callbacks are opening in new windows, or whether some `finish-args` are missing (Like   `- --share=network` and/or `- --talk-name=org.freedesktop.portal.OpenURI`). So, this is what I've got so far, I might have another go at it if I have some time.

**Comment by iskandergaba** [comment]
## Update

Below is my latest version of the manifest

```yml
id: com.bilingify.readest

runtime: org.gnome.Platform
runtime-version: "48"
sdk: org.gnome.Sdk

command: readest
finish-args:
  - --socket=wayland
  - --socket=fallback-x11
  - --device=dri
  - --share=ipc
  - --share=network

modules:
  - name: binary
    buildsystem: simple
    sources:
      - type: file
        url: https://github.com/readest/readest/releases/download/v0.9.37/Readest_0.9.37_amd64.deb
        sha256: 19bead514e592fabf84352db3742fa93be03e82fee1c84bc1acf6ccd5df18305
        only-arches: [x86_64]
      - type: file
        url: https://github.com/readest/readest/releases/download/v0.9.37/Readest_0.9.37_arm64.deb
        sha256: bb36ee60d8b710f376a961317089393707a3106c9e6cbd26d472a872b2f13360
        only-arches: [aarch64]
    build-commands:
      - ar -x *.deb
      - tar -xf data.tar.gz
      - install -Dm755 usr/bin/readest /app/bin/readest
      - install -Dm644 usr/share/applications/Readest.desktop /app/share/applications/com.bilingify.readest.desktop
      - install -Dm644 usr/share/icons/hicolor/128x128/apps/readest.png /app/share/icons/hicolor/128x128/apps/com.bilingify.readest.png
      - install -Dm644 usr/share/icons/hicolor/32x32/apps/readest.png /app/share/icons/hicolor/32x32/apps/com.bilingify.readest.png
      - install -Dm644 usr/share/icons/hicolor/256x256@2/apps/readest.png /app/share/icons/hicolor/256x256/apps/com.bilingify.readest.png
      - install -Dm644 usr/share/icons/hicolor/256x256@2/apps/readest.png /app/share/icons/hicolor/256x256@2/apps/com.bilingify.readest.png
      - install -Dm644 /dev/null /app/share/icons/hicolor/index.theme
      - desktop-file-edit --set-key=Exec --set-value='readest %u' /app/share/applications/com.bilingify.readest.desktop
      - desktop-file-edit --set-key=Icon --set-value='com.bilingify.readest' /app/share/applications/com.bilingify.readest.desktop
      - gtk-update-icon-cache -f /app/share/icons/hicolor
```

**Fixes**
- Add `- --share=network` to enable communication with the internet. Before this addition, Even the login using my email and password account (Not OAuth) failed. After this addition, I can now log in to my account and sync my books using my email and password at least.

**Comment by iskandergaba** [comment]
> Also, the deep link might not be registered at all in flatpak sandbox:
> 
> ```
>                 if has_xdg_mime() {
>                     use tauri_plugin_deep_link::DeepLinkExt;
>                     app.deep_link().register_all()?;
>                 } else {
>                     println!("xdg-mime not found; skipping deep link setup on Linux.");
>                 }
> ```
> 
> If there is no `xdg-mime` in the sandbox (which should be the case for flatpak), the deep link plugin won't work. Ref [here](https://github.com/readest/readest/blob/main/apps/readest-app/src-tauri/src/lib.rs#L226-L231).

This is probably a big part of it. There should be a way of using this in the sandbox. Also, I noticed that some `readest-handler.desktop` is automatically created by the app, and while I suspect it is responsible for handling OAuth callbacks, I think there should be only one `.desktop` file for handling the callbacks and opening the app and files etc. Could be that there is something being mishandled here. Sadly, I am neither a Rust expert nor a TypeScript or Next.js savvy :/

**Comment by chrox** [comment]
Instead of checking the availability of `xdg-mime`, we can also do:
```
use tauri_plugin_deep_link::DeepLinkExt;
let _ = app.deep_link().register_all();
```
to prevent from panic of failed deep link registration.

This is where I stopped investigation. I didn't try the `desktop-file-edit --set-key=Exec --set-value='readest %u'`, which might make some difference.

**Comment by iskandergaba** [comment]
## Update

Below is the latest version of the manifest.
```yml
id: com.bilingify.readest

runtime: org.gnome.Platform
runtime-version: "48"
sdk: org.gnome.Sdk

command: readest
finish-args:
  - --socket=wayland
  - --socket=fallback-x11
  - --socket=pulseaudio
  - --device=dri
  - --share=ipc
  - --share=network

modules:
  - name: binary
    buildsystem: simple
    sources:
      - type: file
        url: https://github.com/readest/readest/releases/download/v0.9.37/Readest_0.9.37_amd64.deb
        sha256: 19bead514e592fabf84352db3742fa93be03e82fee1c84bc1acf6ccd5df18305
        only-arches: [x86_64]
      - type: file
        url: https://github.com/readest/readest/releases/download/v0.9.37/Readest_0.9.37_arm64.deb
        sha256: bb36ee60d8b710f376a961317089393707a3106c9e6cbd26d472a872b2f13360
        only-arches: [aarch64]
    build-commands:
      - ar -x *.deb
      - tar -xf data.tar.gz
      - install -Dm755 usr/bin/readest /app/bin/readest
      - install -Dm644 usr/share/applications/Readest.desktop /app/share/applications/com.bilingify.readest.desktop
      - install -Dm644 usr/share/icons/hicolor/128x128/apps/readest.png /app/share/icons/hicolor/128x128/apps/com.bilingify.readest.png
      - install -Dm644 usr/share/icons/hicolor/32x32/apps/readest.png /app/share/icons/hicolor/32x32/apps/com.bilingify.readest.png
      - install -Dm644 usr/share/icons/hicolor/256x256@2/apps/readest.png /app/share/icons/hicolor/256x256/apps/com.bilingify.readest.png
      - install -Dm644 usr/share/icons/hicolor/256x256@2/apps/readest.png /app/share/icons/hicolor/256x256@2/apps/com.bilingify.readest.png
      - install -Dm644 /dev/null /app/share/icons/hicolor/index.theme
      - desktop-file-edit --set-key=Exec --set-value='readest %u' /app/share/applications/com.bilingify.readest.desktop
      - desktop-file-edit --set-key=Icon --set-value='com.bilingify.readest' /app/share/applications/com.bilingify.readest.desktop
      - gtk-update-icon-cache -f /app/share/icons/hicolor
```

** Fixes
- Fix the TTS not emitting sound due to `- --socket=pulseaudio` missing from `finish-args`.
